#!/bin/bash

# \でスペースをエスケープできる
COMMAND='\         test test test'

# 行数取得
ROW_NUM=`grep -n hoge package.json | sed -e 's/:.*//g'`

# 行挿入
sed -i "${ROW_NUM}a ${COMMAND}" package.json
cat package.json

# 行削除
sed -i "$((++ROW_NUM))d" package.json
cat package.json

echo done! 
